
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calender(object):
    def setupUi(self, Calender):
        Calender.setObjectName("Calender")
        Calender.resize(1117, 765)
        Calender.setStyleSheet("background:rgb(232, 232, 232)\n"
"")
        self.days_combo_4 = QtWidgets.QComboBox(Calender)
        self.days_combo_4.setGeometry(QtCore.QRect(440, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.days_combo_4.setFont(font)
        self.days_combo_4.setStyleSheet("background:rgb(255, 255, 255)")
        self.days_combo_4.setObjectName("days_combo_4")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.days_combo_4.addItem("")
        self.event_list_3 = QtWidgets.QTextBrowser(Calender)
        self.event_list_3.setGeometry(QtCore.QRect(650, 50, 461, 701))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.event_list_3.setFont(font)
        self.event_list_3.setStyleSheet("background:rgb(255, 255, 255)")
        self.event_list_3.setObjectName("event_list_3")
        self.event_detail_2 = QtWidgets.QLineEdit(Calender)
        self.event_detail_2.setGeometry(QtCore.QRect(120, 570, 501, 101))
        self.event_detail_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.event_detail_2.setObjectName("event_detail_2")
        self.check_button_2 = QtWidgets.QPushButton(Calender)
        self.check_button_2.setGeometry(QtCore.QRect(490, 157, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_button_2.setFont(font)
        self.check_button_2.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.check_button_2.setObjectName("check_button_2")
        self.cancel_3 = QtWidgets.QPushButton(Calender)
        self.cancel_3.setGeometry(QtCore.QRect(1000, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_3.setFont(font)
        self.cancel_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background:rgb(126, 143, 255);")
        self.cancel_3.setObjectName("cancel_3")
        self.event_combo_2 = QtWidgets.QComboBox(Calender)
        self.event_combo_2.setGeometry(QtCore.QRect(50, 490, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.event_combo_2.setFont(font)
        self.event_combo_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.event_combo_2.setObjectName("event_combo_2")
        self.event_combo_2.addItem("")
        self.event_combo_2.addItem("")
        self.event_combo_2.addItem("")
        self.event_combo_2.addItem("")
        self.label_7 = QtWidgets.QLabel(Calender)
        self.label_7.setGeometry(QtCore.QRect(20, 570, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.calendar_3 = QtWidgets.QCalendarWidget(Calender)
        self.calendar_3.setGeometry(QtCore.QRect(20, 30, 411, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calendar_3.setFont(font)
        self.calendar_3.setStyleSheet("background:rrgb(0, 0, 0);\n"
"\n"
"alternate-background-color: rgb(92, 165, 255);\n"
"selection-background-color: rgb(141, 209, 104);\n"
"selection-color: rgb(0, 85, 127)")
        self.calendar_3.setObjectName("calendar_3")
        self.label_4 = QtWidgets.QLabel(Calender)
        self.label_4.setGeometry(QtCore.QRect(50, 420, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Calender)
        self.label_3.setGeometry(QtCore.QRect(650, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.submit_2 = QtWidgets.QPushButton(Calender)
        self.submit_2.setGeometry(QtCore.QRect(290, 690, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit_2.setFont(font)
        self.submit_2.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.submit_2.setObjectName("submit_2")
        self.days_combo_3 = QtWidgets.QComboBox(Calender)
        self.days_combo_3.setGeometry(QtCore.QRect(290, 490, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.days_combo_3.setFont(font)
        self.days_combo_3.setStyleSheet("background:rgb(255, 255, 255)")
        self.days_combo_3.setObjectName("days_combo_3")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.days_combo_3.addItem("")
        self.event_name_2 = QtWidgets.QLineEdit(Calender)
        self.event_name_2.setGeometry(QtCore.QRect(120, 410, 321, 31))
        self.event_name_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.event_name_2.setObjectName("event_name_2")
        self.leaveBalance = QtWidgets.QTextBrowser(Calender)
        self.leaveBalance.setGeometry(QtCore.QRect(470, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.leaveBalance.setFont(font)
        self.leaveBalance.setStyleSheet("background:rgb(255, 255, 255)")
        self.leaveBalance.setObjectName("leaveBalance")
        self.label_8 = QtWidgets.QLabel(Calender)
        self.label_8.setGeometry(QtCore.QRect(470, 280, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Calender)
        self.label_9.setGeometry(QtCore.QRect(290, 460, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Calender)
        self.label_10.setGeometry(QtCore.QRect(50, 460, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.welcome = QtWidgets.QTextBrowser(Calender)
        self.welcome.setGeometry(QtCore.QRect(440, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.welcome.setFont(font)
        self.welcome.setObjectName("welcome")
        self.dele = QtWidgets.QPushButton(Calender)
        self.dele.setGeometry(QtCore.QRect(440, 690, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dele.setFont(font)
        self.dele.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.dele.setObjectName("dele")

        self.retranslateUi(Calender)
        QtCore.QMetaObject.connectSlotsByName(Calender)

    def retranslateUi(self, Calender):
        _translate = QtCore.QCoreApplication.translate
        Calender.setWindowTitle(_translate("Calender", "Calender"))
        self.days_combo_4.setItemText(0, _translate("Calender", "Select number of days"))
        self.days_combo_4.setItemText(1, _translate("Calender", "1 day"))
        self.days_combo_4.setItemText(2, _translate("Calender", "2 days"))
        self.days_combo_4.setItemText(3, _translate("Calender", "3 days"))
        self.days_combo_4.setItemText(4, _translate("Calender", "4 days"))
        self.days_combo_4.setItemText(5, _translate("Calender", "5 days"))
        self.days_combo_4.setItemText(6, _translate("Calender", "6 days"))
        self.days_combo_4.setItemText(7, _translate("Calender", "7 days"))
        self.days_combo_4.setItemText(8, _translate("Calender", "8 days"))
        self.days_combo_4.setItemText(9, _translate("Calender", "9 days"))
        self.days_combo_4.setItemText(10, _translate("Calender", "10 days"))
        self.check_button_2.setText(_translate("Calender", "Check"))
        self.cancel_3.setText(_translate("Calender", "Logout"))
        self.event_combo_2.setItemText(0, _translate("Calender", "other"))
        self.event_combo_2.setItemText(1, _translate("Calender", "Doctor"))
        self.event_combo_2.setItemText(2, _translate("Calender", "Marriage"))
        self.event_combo_2.setItemText(3, _translate("Calender", "Family"))
        self.label_7.setText(_translate("Calender", "Description"))
        self.label_4.setText(_translate("Calender", "Reason"))
        self.label_3.setText(_translate("Calender", "Events on Date"))
        self.submit_2.setText(_translate("Calender", "Submit"))
        self.days_combo_3.setItemText(0, _translate("Calender", "1 day"))
        self.days_combo_3.setItemText(1, _translate("Calender", "2 days"))
        self.days_combo_3.setItemText(2, _translate("Calender", "3 days"))
        self.days_combo_3.setItemText(3, _translate("Calender", "4 days"))
        self.days_combo_3.setItemText(4, _translate("Calender", "5 days"))
        self.days_combo_3.setItemText(5, _translate("Calender", "6 days"))
        self.days_combo_3.setItemText(6, _translate("Calender", "7 days"))
        self.days_combo_3.setItemText(7, _translate("Calender", "8 days"))
        self.days_combo_3.setItemText(8, _translate("Calender", "9 days"))
        self.days_combo_3.setItemText(9, _translate("Calender", "10 days"))
        self.label_8.setText(_translate("Calender", "Leave balance"))
        self.label_9.setText(_translate("Calender", "Select Number of days"))
        self.label_10.setText(_translate("Calender", "Select Event"))
        self.dele.setText(_translate("Calender", "Delete Leave"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calender = QtWidgets.QDialog()
    ui = Ui_Calender()
    ui.setupUi(Calender)
    Calender.show()
    sys.exit(app.exec_())
