from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 606)
        Dialog.setStyleSheet("background-color: rgb(56, 58, 89)")
        self.email_text = QtWidgets.QLineEdit(Dialog)
        self.email_text.setGeometry(QtCore.QRect(50, 380, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_text.setFont(font)
        self.email_text.setStyleSheet("background-color: rgb(98, 114, 164)")
        self.email_text.setObjectName("email_text")
        self.pass_text = QtWidgets.QLineEdit(Dialog)
        self.pass_text.setGeometry(QtCore.QRect(50, 430, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pass_text.setFont(font)
        self.pass_text.setStyleSheet("background-color: rgb(98, 114, 164)")
        self.pass_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_text.setObjectName("pass_text")
        self.login_button = QtWidgets.QPushButton(Dialog)
        self.login_button.setGeometry(QtCore.QRect(70, 490, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.login_button.setObjectName("login_button")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(270, 490, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.cancel_button.setObjectName("cancel_button")
        self.forgetpass_button = QtWidgets.QPushButton(Dialog)
        self.forgetpass_button.setGeometry(QtCore.QRect(130, 540, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.forgetpass_button.setFont(font)
        self.forgetpass_button.setStyleSheet("background: rgb(141, 209, 104);\n"
"")
        self.forgetpass_button.setObjectName("forgetpass_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 70, 431, 291))
        self.label.setStyleSheet("image: url(:/newPrefix/lti.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lightmode = QtWidgets.QRadioButton(Dialog)
        self.lightmode.setGeometry(QtCore.QRect(30, 20, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lightmode.setFont(font)
        self.lightmode.setStyleSheet("color:rgb(255, 85, 255)")
        self.lightmode.setObjectName("lightmode")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(290, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:rgb(255, 85, 255)")
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calendar-LogIn"))
        self.email_text.setPlaceholderText(_translate("Dialog", "User ID"))
        self.pass_text.setPlaceholderText(_translate("Dialog", "Password"))
        self.login_button.setText(_translate("Dialog", "Login"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.forgetpass_button.setText(_translate("Dialog", "Forgot Password?"))
        self.lightmode.setText(_translate("Dialog", "Light Mode"))
        self.radioButton_2.setText(_translate("Dialog", "Dark Mode"))
import source_rc
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
