from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(447, 604)
        Dialog.setStyleSheet("background:rgb(232, 232, 232)\n"
"")
        self.email_text = QtWidgets.QLineEdit(Dialog)
        self.email_text.setGeometry(QtCore.QRect(50, 380, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email_text.setFont(font)
        self.email_text.setStyleSheet("background-color: rgb(255,255,255)")
        self.email_text.setObjectName("email_text")
        self.pass_text = QtWidgets.QLineEdit(Dialog)
        self.pass_text.setGeometry(QtCore.QRect(50, 430, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pass_text.setFont(font)
        self.pass_text.setStyleSheet("background-color: rgb(255,255,255)")
        self.pass_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_text.setObjectName("pass_text")
        self.login_button = QtWidgets.QPushButton(Dialog)
        self.login_button.setGeometry(QtCore.QRect(70, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.login_button.setObjectName("login_button")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(270, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.cancel_button.setObjectName("cancel_button")
        self.forgetpass_button = QtWidgets.QPushButton(Dialog)
        self.forgetpass_button.setGeometry(QtCore.QRect(140, 550, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.forgetpass_button.setFont(font)
        self.forgetpass_button.setStyleSheet("background: rgb(141, 209, 104);\n"
"")
        self.forgetpass_button.setObjectName("forgetpass_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 70, 431, 291))
        self.label.setStyleSheet("image: url(:/newPrefix/lti.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lightmode = QtWidgets.QRadioButton(Dialog)
        self.lightmode.setGeometry(QtCore.QRect(20, 20, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lightmode.setFont(font)
        self.lightmode.setStyleSheet("color:rgb(53, 53, 53)")
        self.lightmode.setObjectName("lightmode")
        self.darkmade = QtWidgets.QRadioButton(Dialog)
        self.darkmade.setGeometry(QtCore.QRect(290, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.darkmade.setFont(font)
        self.darkmade.setStyleSheet("color:rgb(53, 53, 53)")
        self.darkmade.setObjectName("darkmade")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calendar-LogIn"))
        self.email_text.setPlaceholderText(_translate("Dialog", "User ID"))
        self.pass_text.setPlaceholderText(_translate("Dialog", "Password"))
        self.login_button.setText(_translate("Dialog", "Login"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.forgetpass_button.setText(_translate("Dialog", "Forgot Password?"))
        self.lightmode.setText(_translate("Dialog", "Light Mode"))
        self.darkmade.setText(_translate("Dialog", "Dark Mode"))
import source_rc
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
