# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newpass1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newp1(object):
    def setupUi(self, newp1):
        newp1.setObjectName("newp1")
        newp1.resize(400, 252)
        newp1.setStyleSheet("background-color: rgb(56, 58, 89)")
        self.pass2 = QtWidgets.QLineEdit(newp1)
        self.pass2.setGeometry(QtCore.QRect(70, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pass2.setFont(font)
        self.pass2.setStyleSheet("background-color: rgb(98, 114, 164)")
        self.pass2.setText("")
        self.pass2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass2.setObjectName("pass2")
        self.ok = QtWidgets.QPushButton(newp1)
        self.ok.setGeometry(QtCore.QRect(50, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(newp1)
        self.cancel.setGeometry(QtCore.QRect(260, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.cancel.setObjectName("cancel")
        self.pass1 = QtWidgets.QLineEdit(newp1)
        self.pass1.setGeometry(QtCore.QRect(70, 40, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pass1.setFont(font)
        self.pass1.setStyleSheet("background-color: rgb(98, 114, 164)")
        self.pass1.setText("")
        self.pass1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass1.setObjectName("pass1")

        self.retranslateUi(newp1)
        QtCore.QMetaObject.connectSlotsByName(newp1)

    def retranslateUi(self, newp1):
        _translate = QtCore.QCoreApplication.translate
        newp1.setWindowTitle(_translate("newp1", "Dialog"))
        self.pass2.setPlaceholderText(_translate("newp1", "Renter new password"))
        self.ok.setText(_translate("newp1", "OK"))
        self.cancel.setText(_translate("newp1", "Cancel"))
        self.pass1.setPlaceholderText(_translate("newp1", "Enter new password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newp1 = QtWidgets.QDialog()
    ui = Ui_newp1()
    ui.setupUi(newp1)
    newp1.show()
    sys.exit(app.exec_())
