# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OTP(object):
    def setupUi(self, OTP):
        OTP.setObjectName("OTP")
        OTP.resize(400, 319)
        self.userid = QtWidgets.QLineEdit(OTP)
        self.userid.setGeometry(QtCore.QRect(30, 40, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userid.setFont(font)
        self.userid.setText("")
        self.userid.setObjectName("userid")
        self.sendotp = QtWidgets.QPushButton(OTP)
        self.sendotp.setGeometry(QtCore.QRect(140, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sendotp.setFont(font)
        self.sendotp.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.sendotp.setObjectName("sendotp")
        self.otp = QtWidgets.QLineEdit(OTP)
        self.otp.setGeometry(QtCore.QRect(30, 160, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.otp.setFont(font)
        self.otp.setText("")
        self.otp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.otp.setObjectName("otp")
        self.ok = QtWidgets.QPushButton(OTP)
        self.ok.setGeometry(QtCore.QRect(60, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("background: rgb(141, 209, 104);\n"
"color: rgb(255,255,255)")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(OTP)
        self.cancel.setGeometry(QtCore.QRect(230, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background:rgb(126, 143, 255);")
        self.cancel.setObjectName("cancel")

        self.retranslateUi(OTP)
        QtCore.QMetaObject.connectSlotsByName(OTP)

    def retranslateUi(self, OTP):
        _translate = QtCore.QCoreApplication.translate
        OTP.setWindowTitle(_translate("OTP", "Send OTP"))
        self.userid.setPlaceholderText(_translate("OTP", "User ID"))
        self.sendotp.setText(_translate("OTP", "Send OTP"))
        self.otp.setPlaceholderText(_translate("OTP", "Enter OTP"))
        self.ok.setText(_translate("OTP", "OK"))
        self.cancel.setText(_translate("OTP", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OTP = QtWidgets.QDialog()
    ui = Ui_OTP()
    ui.setupUi(OTP)
    OTP.show()
    sys.exit(app.exec_())
