# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otp1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OTP1(object):
    def setupUi(self, OTP1):
        OTP1.setObjectName("OTP1")
        OTP1.resize(400, 306)
        OTP1.setStyleSheet("background-color: rgb(56, 58, 89)")
        self.sendotp = QtWidgets.QPushButton(OTP1)
        self.sendotp.setGeometry(QtCore.QRect(140, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sendotp.setFont(font)
        self.sendotp.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.sendotp.setObjectName("sendotp")
        self.userid = QtWidgets.QLineEdit(OTP1)
        self.userid.setGeometry(QtCore.QRect(30, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.userid.setFont(font)
        self.userid.setStyleSheet("background-color: rgb(98, 114, 164)")
        self.userid.setText("")
        self.userid.setObjectName("userid")
        self.ok = QtWidgets.QPushButton(OTP1)
        self.ok.setGeometry(QtCore.QRect(60, 240, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(OTP1)
        self.cancel.setGeometry(QtCore.QRect(230, 240, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.cancel.setObjectName("cancel")
        self.otp = QtWidgets.QLineEdit(OTP1)
        self.otp.setGeometry(QtCore.QRect(30, 140, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.otp.setFont(font)
        self.otp.setStyleSheet("background-color: rgb(98, 114, 164)")
        self.otp.setText("")
        self.otp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.otp.setObjectName("otp")

        self.retranslateUi(OTP1)
        QtCore.QMetaObject.connectSlotsByName(OTP1)

    def retranslateUi(self, OTP1):
        _translate = QtCore.QCoreApplication.translate
        OTP1.setWindowTitle(_translate("OTP1", "Dialog"))
        self.sendotp.setText(_translate("OTP1", "Send OTP"))
        self.userid.setPlaceholderText(_translate("OTP1", "User ID"))
        self.ok.setText(_translate("OTP1", "OK"))
        self.cancel.setText(_translate("OTP1", "Cancel"))
        self.otp.setPlaceholderText(_translate("OTP1", "Enter OTP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OTP1 = QtWidgets.QDialog()
    ui = Ui_OTP1()
    ui.setupUi(OTP1)
    OTP1.show()
    sys.exit(app.exec_())
