# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sure1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sure1(object):
    def setupUi(self, sure1):
        sure1.setObjectName("sure1")
        sure1.resize(356, 196)
        sure1.setStyleSheet("background-color: rgb(56, 58, 89)")
        self.yeah = QtWidgets.QPushButton(sure1)
        self.yeah.setGeometry(QtCore.QRect(40, 120, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yeah.setFont(font)
        self.yeah.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.yeah.setObjectName("yeah")
        self.label = QtWidgets.QLabel(sure1)
        self.label.setGeometry(QtCore.QRect(100, 40, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(254, 121, 199);")
        self.label.setObjectName("label")
        self.nah = QtWidgets.QPushButton(sure1)
        self.nah.setGeometry(QtCore.QRect(220, 120, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nah.setFont(font)
        self.nah.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));")
        self.nah.setObjectName("nah")

        self.retranslateUi(sure1)
        QtCore.QMetaObject.connectSlotsByName(sure1)

    def retranslateUi(self, sure1):
        _translate = QtCore.QCoreApplication.translate
        sure1.setWindowTitle(_translate("sure1", "Dialog"))
        self.yeah.setText(_translate("sure1", "Yes"))
        self.label.setText(_translate("sure1", "Are You Sure?"))
        self.nah.setText(_translate("sure1", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sure1 = QtWidgets.QDialog()
    ui = Ui_sure1()
    ui.setupUi(sure1)
    sure1.show()
    sys.exit(app.exec_())
